import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination } from "swiper/modules";

/**
 * Course card component for individual course display
 * @param title - Course title
 * @param description - Course description
 * @param date - Course date
 * @param instructor - Course instructor
 */
interface CourseCardProps {
  title: string;
  description: string;
  date: string;
  instructor: string;
}

function CourseCard({ title, description, date, instructor }: CourseCardProps) {
  return (
    <div className="bg-white rounded-lg shadow-md p-6 mx-2 h-64">
      <div className="h-full flex flex-col justify-between">
        <div>
          <h3 className="text-lg font-semibold text-gray-800 mb-2">{title}</h3>
          <p className="text-gray-600 text-sm mb-3 line-clamp-3">
            {description}
          </p>
        </div>
        <div className="space-y-2">
          <div className="flex items-center text-sm text-gray-500">
            <span className="font-medium">日期：</span>
            <span>{date}</span>
          </div>
          <div className="flex items-center text-sm text-gray-500">
            <span className="font-medium">講師：</span>
            <span>{instructor}</span>
          </div>
        </div>
      </div>
    </div>
  );
}

/**
 * Courses page component
 * Displays church courses and classes with Swiper navigation
 */
function CoursesPage() {
  // Sample course data - replace with actual data from API
  const courses = [
    {
      id: 1,
      title: "聖經研讀班",
      description:
        "深入研讀聖經，了解神的話語，建立穩固的信仰根基。適合所有信徒參與。",
      date: "2024年2月15日",
      instructor: "王牧師",
    },
    {
      id: 2,
      title: "青年團契",
      description: "年輕人的聚會，透過分享、禱告和活動，建立彼此的友誼和信仰。",
      date: "2024年2月20日",
      instructor: "李傳道",
    },
    {
      id: 3,
      title: "婚姻輔導課程",
      description: "幫助夫妻建立美滿的婚姻關係，學習聖經中的婚姻原則。",
      date: "2024年2月25日",
      instructor: "陳牧師",
    },
    {
      id: 4,
      title: "兒童主日學",
      description: "專為兒童設計的聖經課程，透過故事和活動學習神的愛。",
      date: "2024年3月1日",
      instructor: "張老師",
    },
    {
      id: 5,
      title: "禱告會",
      description: "集體禱告的時間，為教會、家庭和社區的需要代禱。",
      date: "2024年3月5日",
      instructor: "林長老",
    },
  ];

  return (
    <div className="h-full bg-gray-50 py-8">
      <div className="container mx-auto px-4">
        {/* Header Section */}
        {/* <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-800 mb-2">
            PWA 最新課程
          </h1>
          <p className="text-gray-600">探索我們最新的課程和活動</p>
        </div> */}

        {/* Swiper Section */}
        <div className="relative">
          {/* Custom Pagination - Penpot Design */}
          <div className="custom-pagination flex justify-center items-center space-x-3 mt-6 mb-6">
            {/* Pagination bullets will be dynamically generated by Swiper */}
          </div>

          <Swiper
            modules={[Navigation, Pagination]}
            spaceBetween={20}
            slidesPerView={1}
            // navigation={{
            //   nextEl: ".swiper-button-next-custom",
            //   prevEl: ".swiper-button-prev-custom",
            // }}
            pagination={{
              clickable: true,
              dynamicBullets: false,
              el: ".custom-pagination",
              bulletClass: "custom-bullet",
              bulletActiveClass: "custom-bullet-active",
            }}
            breakpoints={{
              640: {
                slidesPerView: 2,
                spaceBetween: 20,
              },
              768: {
                slidesPerView: 2,
                spaceBetween: 30,
              },
              1024: {
                slidesPerView: 3,
                spaceBetween: 30,
              },
            }}
            className="pb-16"
          >
            {courses.map((course) => (
              <SwiperSlide key={course.id}>
                <CourseCard
                  title={course.title}
                  description={course.description}
                  date={course.date}
                  instructor={course.instructor}
                />
              </SwiperSlide>
            ))}
          </Swiper>

          {/* Custom Navigation Buttons */}
          {/* <div className="swiper-button-prev-custom absolute left-0 top-1/2 -translate-y-1/2 z-10 w-10 h-10 bg-white rounded-full shadow-lg flex items-center justify-center cursor-pointer hover:bg-gray-50 transition-colors">
            <svg
              className="w-5 h-5 text-gray-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M15 19l-7-7 7-7"
              />
            </svg>
          </div>
          <div className="swiper-button-next-custom absolute right-0 top-1/2 -translate-y-1/2 z-10 w-10 h-10 bg-white rounded-full shadow-lg flex items-center justify-center cursor-pointer hover:bg-gray-50 transition-colors">
            <svg
              className="w-5 h-5 text-gray-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 5l7 7-7 7"
              />
            </svg>
          </div> */}
        </div>

        {/* Additional Info Section */}
        {/* <div className="mt-12 text-center">
          <p className="text-gray-600 mb-4">想了解更多課程資訊？</p>
          <button className="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition-colors">
            聯絡我們
          </button>
        </div> */}
      </div>
    </div>
  );
}

export default CoursesPage;
